[project]
name = "J-IGNO"
version = "0.1.0"
description = "JAX port of IGNO and MSc Code"
readme = "README.md"
requires-python = ">=3.11,<3.12.0"

dependencies = [
    "flax>=0.12.2",
    "h5py>=3.15.1",
    "jax<0.9.0; platform_system == 'Darwin'",
    "jax[cuda12]<0.9.0; platform_system == 'Linux'",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "optax>=0.2.6",
    "pandas>=3.0.0",
    "pytest>=9.0.2",
    "scienceplots>=2.2.0",
    "scipy>=1.17.0",
    "tensorboardx>=2.6.4",
    "tqdm>=4.67.1",
]


[project.optional-dependencies]
dev = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "notebook>=7.5.3",
]




