run_name: alpha_8
artifact_root: runs
seed: 10086
problem:
  type: darcy_continuous
  train_data: ./data/darcy_continuous/smh_train.mat
  test_data: ./data/darcy_continuous/smh_test_in.mat
pretrained: null
training:
  epochs: 12500
  batch_size: 50
  epoch_show: 200
  loss_weights:
    pde: 0.25
    data: 2.0
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 1.0e-06
  scheduler:
    type: StepLR
    step_size: 2500
    gamma: 0.5
    eta_min: null
    pct_start: 0.3
    div_factor: 25.0
    final_div_factor: 10000.0
evaluation:
  method: igno
  batch_size: 200
  n_obs: 100
  obs_sampling: random
  snr_db: null
  inversion:
    epochs: 500
    loss_weights:
      pde: 1.0
      data: 1.0
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.0
    scheduler:
      type: null
      step_size: null
      gamma: null
      eta_min: null
      pct_start: 0.3
      div_factor: 25.0
      final_div_factor: 10000.0
  results_dir: results
